### ISSUE TITLE
ioBroker Adapter down beim steuern von PV-Überschuss max_watts

### ISSUE THREAD

**Issue by teamworkdigital** [MK-2001/ioBroker.go-e#135]
iobroker und den Adapter für go-e (1.0.22) in aktueller Version. 
go-eCharger V3. 
Steuern per Blockly des PV-Überschusswertes führt zu einem Absturz des Adapters.
Alle anderen Werte kann ich steuern. nur wenn ich die Leistung verstellen möchte, stürzt der Adapter ab.
Dabei ist es aber egal, ob ich den Wert für amp, 

go-e.0 | 2022-04-29 12:14:39.134 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
go-e.0 | 2022-04-29 12:14:39.133 | info | terminating
go-e.0 | 2022-04-29 12:14:39.115 | error | Cannot read property 'finish' of undefined
go-e.0 | 2022-04-29 12:14:39.115 | error | TypeError: Cannot read property 'finish' of undefined at GoE.updateAmpLevel (/opt/iobroker/node_modules/iobroker.go-e/main.js:678:25)
go-e.0 | 2022-04-29 12:14:39.114 | error | unhandled promise rejection: Cannot read property 'finish' of undefined
go-e.0 | 2022-04-29 12:14:39.114 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
go-e.0 | 2022-04-29 12:14:39.109 | info | Set value 11 of id amp
go-e.0 | 2022-04-29 12:14:39.020 | info | Set value 1 of id alw
go-e.0 | 2022-04-29 12:14:12.811 | warn | Sentry enabled. You can switch it off in settings of the adapter.
go-e.0 | 2022-04-29 12:14:12.811 | info | Intervall: 30
go-e.0 | 2022-04-29 12:14:12.810 | info | Server: 192.168.133.18
go-e.0 | 2022-04-29 12:14:12.775 | info | starting. Version 1.0.22 in /opt/iobroker/node_modules/iobroker.go-e, node: v12.22.12, js-controller: 4.0.23
-- | -- | --

Auch das senden der Werte über die Adapter-PV-Überschussfunktion geht auf Fehler:

go-e.0 | 2022-04-29 12:50:08.017 | info | Intervall: 30
-- | -- | --
go-e.0 | 2022-04-29 12:50:08.016 | info | Server: 192.168.133.18
go-e.0 | 2022-04-29 12:50:07.979 | info | starting. Version 1.0.22 in /opt/iobroker/node_modules/iobroker.go-e, node: v12.22.12, js-controller: 4.0.23
go-e.0 | 2022-04-29 12:49:34.219 | error | Cannot read property 'finish' of undefined
go-e.0 | 2022-04-29 12:49:34.218 | error | TypeError: Cannot read property 'finish' of undefined at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25) at runNextTicks (internal/process/task_queues.js:62:5) at processImmediate (internal/timers.js:434:9)
go-e.0 | 2022-04-29 12:49:34.218 | error | unhandled promise rejection: Cannot read property 'finish' of undefined
go-e.0 | 2022-04-29 12:49:34.217 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
go-e.0 | 2022-04-29 12:49:34.214 | info | Set value 23 of id amx
go-e.0 | 2022-04-29 12:49:34.183 | error | Cannot read property 'finish' of undefined

**Comment by teamworkdigital** [comment]
iobroker und den Adapter für go-e (1.0.22) in aktueller Version. 
go-eCharger V3. 
Steuern per Blockly des PV-Überschusswertes führt zu einem Absturz des Adapters.
Alle anderen Werte kann ich steuern. nur wenn ich die Leistung verstellen möchte, stürzt der Adapter ab.
Dabei ist es aber egal, ob ich den Wert für amp, 


go-e.0 | 2022-04-29 12:14:39.134 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
go-e.0 | 2022-04-29 12:14:39.133 | info | terminating
go-e.0 | 2022-04-29 12:14:39.115 | error | Cannot read property 'finish' of undefined
go-e.0 | 2022-04-29 12:14:39.115 | error | TypeError: Cannot read property 'finish' of undefined at GoE.updateAmpLevel (/opt/iobroker/node_modules/iobroker.go-e/main.js:678:25)
go-e.0 | 2022-04-29 12:14:39.114 | error | unhandled promise rejection: Cannot read property 'finish' of undefined
go-e.0 | 2022-04-29 12:14:39.114 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
go-e.0 | 2022-04-29 12:14:39.109 | info | Set value 11 of id amp
go-e.0 | 2022-04-29 12:14:39.020 | info | Set value 1 of id alw
go-e.0 | 2022-04-29 12:14:12.811 | warn | Sentry enabled. You can switch it off in settings of the adapter.
go-e.0 | 2022-04-29 12:14:12.811 | info | Intervall: 30
go-e.0 | 2022-04-29 12:14:12.810 | info | Server: 192.168.133.18
go-e.0 | 2022-04-29 12:14:12.775 | info | starting. Version 1.0.22 in /opt/iobroker/node_modules/iobroker.go-e, node: v12.22.12, js-controller: 4.0.23

Auch das senden der Werte über die Adapter-PV-Überschussfunktion geht auf Fehler:



2022-04-29 12:50:08.017 | info | Intervall: 30
-- | -- | --
go-e.0 | 2022-04-29 12:50:08.016 | info | Server: 192.168.133.18
go-e.0 | 2022-04-29 12:50:07.979 | info | starting. Version 1.0.22 in /opt/iobroker/node_modules/iobroker.go-e, node: v12.22.12, js-controller: 4.0.23
go-e.0 | 2022-04-29 12:49:34.219 | error | Cannot read property 'finish' of undefined
go-e.0 | 2022-04-29 12:49:34.218 | error | TypeError: Cannot read property 'finish' of undefined at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25) at runNextTicks (internal/process/task_queues.js:62:5) at processImmediate (internal/timers.js:434:9)
go-e.0 | 2022-04-29 12:49:34.218 | error | unhandled promise rejection: Cannot read property 'finish' of undefined
go-e.0 | 2022-04-29 12:49:34.217 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
go-e.0 | 2022-04-29 12:49:34.214 | info | Set value 23 of id amx
go-e.0 | 2022-04-29 12:49:34.183 | error | Cannot read property 'finish' of undefined
