### ISSUE TITLE
Adapter crashes 

### ISSUE THREAD

**Issue by keksn** [MK-2001/ioBroker.go-e#137]
2022-05-10 16:52:00.587	warn	Could not perform strict object check of state go-e.0.energy.phase3.voltage: DB closed

go-e.0
2022-05-10 16:52:00.585	warn	Could not perform strict object check of state go-e.0.energy.phase2.voltage: DB closed

go-e.0
2022-05-10 16:52:00.582	warn	Could not perform strict object check of state go-e.0.energy.phase1.voltage: DB closed

go-e.0
2022-05-10 16:52:00.520	info	200 with message: OK

go-e.0
2022-05-10 16:52:00.071	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

go-e.0
2022-05-10 16:52:00.069	info	terminating

go-e.0
2022-05-10 16:52:00.060	error	Cannot read property 'finish' of undefined

go-e.0
2022-05-10 16:52:00.060	error	TypeError: Cannot read property 'finish' of undefined at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)

go-e.0
2022-05-10 16:52:00.059	error	unhandled promise rejection: Cannot read property 'finish' of undefined

go-e.0
2022-05-10 16:52:00.058	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

go-e.0
2022-05-10 16:52:00.050	info	Set value 10 of id amx

go-e.0
2022-05-10 16:51:34.757	info	Intervall: 60

go-e.0
2022-05-10 16:51:34.756	info	Server: 192.168.1.117

go-e.0
2022-05-10 16:51:34.692	info	starting. Version 1.0.22 (non-npm: MK-2001/ioBroker.go-e#22cca4245144c9bc2baf5594daa833765aa119ed) in /opt/iobroker/node_modules/iobroker.go-e, node: v14.19.2, js-controller: 4.0.23

go-e.0
2022-05-10 16:51:00.589	warn	Could not perform strict object check of state go-e.0.unlocked_by: DB closed

go-e.0
2022-05-10 16:51:00.586	warn	Could not perform strict object check of state go-e.0.adapter_in: DB closed

go-e.0
2022-05-10 16:51:00.582	warn	Cloud not store temperature array to single values, because of error DB closed

go-e.0
2022-05-10 16:51:00.219	info	200 with message: OK

go-e.0
2022-05-10 16:51:00.060	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

go-e.0
2022-05-10 16:51:00.059	info	terminating

go-e.0
2022-05-10 16:51:00.048	error	Cannot read property 'finish' of undefined

go-e.0
2022-05-10 16:51:00.046	error	TypeError: Cannot read property 'finish' of undefined at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)

go-e.0
2022-05-10 16:51:00.045	error	unhandled promise rejection: Cannot read property 'finish' of undefined

go-e.0
2022-05-10 16:51:00.044	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

go-e.0
2022-05-10 16:51:00.037	info	Set value 10 of id amx

go-e.0
2022-05-10 16:50:48.470	info	Intervall: 60

go-e.0
2022-05-10 16:50:48.468	info	Server: 192.168.1.117

go-e.0
2022-05-10 16:50:48.406	info	starting. Version 1.0.22 (non-npm: MK-2001/ioBroker.go-e#22cca4245144c9bbaf5594daa833765aa119ed) in /opt/iobroker/node_modules/iobroker.go-e, node: v14.19.2, js-controller: 4.0.23

**Comment by MK-2001** [comment]
Gleiche wie #143; Sollte nun mit version 1.0.25 behoben sein.
