### ISSUE TITLE
"adjustAmpLevelInWatts"  verursacht Absturz des Adapters

### ISSUE THREAD

**Issue by keksn** [MK-2001/ioBroker.go-e#139]
Ich verwende diesen Datenpunkt schon seit fast einem Jahr in einem Blockly Programm für die Überschussladung.  Seit kurzem verursacht dieses beschreiben des Datenpunkts den Absturz des Adapters. Das Programm wurde nicht verändert. Ich habe schon andere Versionen des Adapters und auch andere Firmware auf dem Go-eCharger probiert....ohne Erfolg.

2022-05-16 17:54:00.201	info	200 with message: OK
 
go-e.0
2022-05-16 17:54:00.087	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
 
go-e.0
2022-05-16 17:54:00.086	info	terminating
 
go-e.0
2022-05-16 17:54:00.075	error	Cannot read property 'finish' of undefined
 
go-e.0
2022-05-16 17:54:00.075	error	TypeError: Cannot read property 'finish' of undefined at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
 
go-e.0
2022-05-16 17:54:00.074	error	unhandled promise rejection: Cannot read property 'finish' of undefined
 
go-e.0
2022-05-16 17:54:00.074	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 
go-e.0
2022-05-16 17:54:00.071	debug	set maxAmperes (amx) by adjustAmpLevelInWatts: 10 with 1023 watts
 
go-e.0
2022-05-16 17:54:00.066	info	Set value 10 of id amx
 
go-e.0
2022-05-16 17:54:00.063	debug	Current used 1392 Watts with 6 Ampere (sum) by 1Phases and adjusting this with 1023 watts by 232 Volts (avg) to new max of 10 Amperes per Phase
 
go-e.0
2022-05-16 17:53:35.848	debug	{"version":"B","tme":"1605221753","rbc":"72","rbt":"272308637","car":"2","amx":"6","amp":"6","err":"0","ast":"0","alw":"1","stp":"0","cbl":"32","pha":"57","fsp":"1","tma":[43.125,46.125],"dws":"1549395","dwo":"180","adi":"1","uby":"0","eto":"52834","wst":"3","fwv":"053.3","nrg":[232,233,233,1,61,0,0,14,0,0,0,145,100,1,0,90],"sse":"050634","wss":"Home1","wke":"********","wen":"1","cdi":"0","tof":"101","tds":"1","lbr":"255","aho":"0","afi":"6","azo":"0","ama":"16","al1":"6","al2":"10","al3":"12","al4":"14","al5":"16","cid":"255","cch":"65535","cfi":"65280","lse":"1","ust":"0","wak":"********","r1x":"2","dto":"0","nmo":"0","sch":"AAAAAAAAAAAAAAAA","sdp":"0","eca":"0","ecr":"0","ecd":"0","ec4":"0","ec5":"0","ec6":"0","ec7":"0","ec8":"0","ec9":"0","ec1":"0","rca":"1","rcr":"","rcd":"","rc4":"","rc5":"","rc6":"","rc7":"","rc8":"","rc9":"","rc1":"","rna":"User 1","rnm":"User 2","rne":"User 3","rn4":"User 4","rn5":"User 5","rn6":"User 6","rn7":"User 7","rn8":"User 8","rn9":"User 9","rn1":"User 10","loe":0,"lot":32,"lom":6,"lop":50,"log":"","lof":0,"loa":0,"lch":271543}
 
go-e.0
2022-05-16 17:53:35.848	debug	Response: 200 - OK with data as object
 
go-e.0
2022-05-16 17:53:35.617	debug	Starte Abfrage an: http://192.168.1.117/status
 
go-e.0
2022-05-16 17:53:35.613	info	Intervall: 60
 
go-e.0
2022-05-16 17:53:35.612	info	Server: 192.168.1.117
 
go-e.0
2022-05-16 17:53:35.574	info	starting. Version 1.0.22 (non-npm: MK-2001/ioBroker.go-e#22cca4245144c9bc2baf5594daa833765aa119ed) in /opt/iobroker/node_modules/iobroker.go-e, node: v14.19.2, js-controller: 4.0.23
 
go-e.0
2022-05-16 17:53:00.086	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
 
go-e.0
2022-05-16 17:53:00.085	info	terminating
 
go-e.0
2022-05-16 17:53:00.082	error	Cannot read property 'finish' of undefined
 
go-e.0
2022-05-16 17:53:00.081	error	TypeError: Cannot read property 'finish' of undefined at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
 
go-e.0
2022-05-16 17:53:00.081	error	unhandled promise rejection: Cannot read property 'finish' of undefined
 
go-e.0
2022-05-16 17:53:00.080	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 
go-e.0
2022-05-16 17:53:00.077	debug	set maxAmperes (amx) by adjustAmpLevelInWatts: 6 amperes by -870 watts
 
go-e.0
2022-05-16 17:53:00.068	info	Set value 6 of id amx
 
go-e.0
2022-05-16 17:53:00.064	debug	Current used 1386 Watts with 6 Ampere (sum) by 1Phases and adjusting this with -870 watts by 231 Volts (avg) to new max of 2 Amperes per Phase
 
go-e.0
2022-05-16 17:52:34.915	debug	{"version":"B","tme":"1605221752","rbc":"72","rbt":"272247708","car":"2","amx":"6","amp":"6","err":"0","ast":"0","alw":"1","stp":"0","cbl":"32","pha":"57","fsp":"1","tma":[43.25,46],"dws":"1540621","dwo":"180","adi":"1","uby":"0","eto":"52834","wst":"3","fwv":"053.3","nrg":[231,233,232,1,61,0,0,14,0,0,0,145,100,1,0,92],"sse":"050634","wss":"Home1","wke":"********","wen":"1","cdi":"0","tof":"101","tds":"1","lbr":"255","aho":"0","afi":"6","azo":"0","ama":"16","al1":"6","al2":"10","al3":"12","al4":"14","al5":"16","cid":"255","cch":"65535","cfi":"65280","lse":"1","ust":"0","wak":"********","r1x":"2","dto":"0","nmo":"0","sch":"AAAAAAAAAAAAAAAA","sdp":"0","eca":"0","ecr":"0","ecd":"0","ec4":"0","ec5":"0","ec6":"0","ec7":"0","ec8":"0","ec9":"0","ec1":"0","rca":"1","rcr":"","rcd":"","rc4":"","rc5":"","rc6":"","rc7":"","rc8":"","rc9":"","rc1":"","rna":"User 1","rnm":"User 2","rne":"User 3","rn4":"User 4","rn5":"User 5","rn6":"User 6","rn7":"User 7","rn8":"User 8","rn9":"User 9","rn1":"User 10","loe":0,"lot":32,"lom":6,"lop":50,"log":"","lof":0,"loa":0,"lch":271543}
 
go-e.0
2022-05-16 17:52:34.915	debug	Response: 200 - OK with data as object
 
go-e.0
2022-05-16 17:52:34.830	debug	Starte Abfrage an: http://192.168.1.117/status
 
go-e.0
2022-05-16 17:52:34.825	info	Intervall: 60
 
go-e.0
2022-05-16 17:52:34.823	info	Server: 192.168.1.117
 
go-e.0
2022-05-16 17:52:34.778	info	starting. Version 1.0.22 (non-npm: MK-2001/ioBroker.go-e#22cca4245144c9bc2baf5594daa833765aa119ed) in /opt/iobroker/node_modules/iobroker.go-e, node: v14.19.2, js-controller: 4.0.23
 
go-e.0
2022-05-16 17:52:00.357	info	200 with message: OK
 
go-e.0
2022-05-16 17:52:00.082	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
 
go-e.0
2022-05-16 17:52:00.081	info	terminating

**Comment by MK-2001** [comment]
Gleiche wie #143; Sollte nun mit Version 1.0.25 behoben sein.

**Comment by keksn** [comment]
Perfekt!! Vielen Dank! LG

Marcus K ***@***.***> schrieb am Sa. 2. Juli 2022 um 22:48:
