### ISSUE TITLE
Feature: PV Überschuss - Hausverbrauch bei Auslesen von Smartmetern

### ISSUE THREAD

**Issue by luckyheiko** [MK-2001/ioBroker.go-e#146]
Hallo 

es ist kein 'Fehler', aber ein Problem das ich habe
![grafik](https://user-images.githubusercontent.com/26415601/178096943-b59c11cd-1d6e-4c48-b86f-126b6d0f353a.png)

bei mir wird der PV Ertrag und die Einspeißung an den Smartmetern ausgelesen
![grafik](https://user-images.githubusercontent.com/26415601/178096968-02184126-67ee-4ca1-85c0-b338e4efdbcf.png)

hier bekomme ich werte immer mit - (Minus)
z.B. -5000W (PV) und -4500W (Einspeißung), würde dann ergeben das ich 500Watt selbst Verbrauche.
leider passt das aber nicht mit der Info das alle Werte + sein müssen.

auch kann ich nicht den Hausverbrauch sondern nur die Einspeißung angeben.

könnte man das implementieren? 
oder könntest mir einen Tipp geben, wie ich das umsetzen kann?

Vielen Dank

**Comment by heikowe** [comment]
Du kannst mit einem eigenen Skript eine User-Variable in den Objekten ablegen, die den Wert des Smartmeters mit + Werten speichert. Und dann den bei den Go-E Settings verwenden.

Mir ist aber noch nicht klar, wo der Go-E Adapter dann das Ergebnis (PV-Leistung - Verbrauch) abspeichert. In go-e.0.energy.adjustAmpLevelInWatts wird ja nur ein festgelegter Offset Wert gespeichert.

**Comment by MK-2001** [comment]
adjustAmpLevelInWatts liest am angeschlossenen Auto, wie viele Phasen derzeit laden. Trägst du dort deinen Überschuss von z. B. 360 W ein, wird der Adapter um 3 A mehr greifen, sofern dein Auto mit einer Phase lädt und nur 1A wenn dein Auto mit drei Phasen lädt.

**Comment by MK-2001** [comment]
> Hallo 
> 
> 
> 
> es ist kein 'Fehler', aber ein Problem das ich habe
> 
> ![grafik](https://user-images.githubusercontent.com/26415601/178096943-b59c11cd-1d6e-4c48-b86f-126b6d0f353a.png)
> 
> 
> 
> bei mir wird der PV Ertrag und die Einspeißung an den Smartmetern ausgelesen
> 
> ![grafik](https://user-images.githubusercontent.com/26415601/178096968-02184126-67ee-4ca1-85c0-b338e4efdbcf.png)
> 
> 
> 
> hier bekomme ich werte immer mit - (Minus)
> 
> z.B. -5000W (PV) und -4500W (Einspeißung), würde dann ergeben das ich 500Watt selbst Verbrauche.
> 
Was sind denn die 3772 in deinem Screenshot PV gesamt, Überschuss?

**Comment by luckyheiko** [comment]
hmm, irgenwo hab ich wohl nen fehler
<html><body>


2022-08-07 08:10:00.016  - error:  go-e.0 (23835) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
--
2022-08-07 08:10:00.018  - error: go-e.0 (23835) unhandled promise rejection: Cannot read properties of undefined (reading 'finish')
2022-08-07 08:10:00.018  - error: go-e.0 (23835) TypeError: Cannot read properties of undefined (reading 'finish')
at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
2022-08-07 08:10:00.018  - error: go-e.0 (23835) Cannot read properties of undefined (reading 'finish')
2022-08-07 08:10:03.186  - error:  host.der-ripper Caught by controller[0]: This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-08-07 08:10:03.186  - error: host.der-ripper Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'finish')
2022-08-07 08:10:03.186  - error:  host.der-ripper Caught by controller[1]:     at  GoE.adjustAmpLevelInWatts  (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
2022-08-07 08:10:03.186  - error: host.der-ripper instance system.adapter.go-e.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-08-07 08:10:03.186  - info: host.der-ripper Restart adapter system.adapter.go-e.0 because enabled
2022-08-07 08:10:33.222  - info: host.der-ripper instance system.adapter.go-e.0 started with pid 23850
2022-08-07 08:11:00.012  - error:  go-e.0 (23850) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-08-07 08:11:00.014  - error: go-e.0 (23850) unhandled promise rejection: Cannot read properties of undefined (reading 'finish')
2022-08-07 08:11:00.014  - error: go-e.0 (23850) TypeError: Cannot read properties of undefined (reading 'finish')
at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
2022-08-07 08:11:00.015  - error: go-e.0 (23850) Cannot read properties of undefined (reading 'finish')
2022-08-07 08:11:03.161  - error:  host.der-ripper Caught by controller[0]: This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-08-07 08:11:03.161  - error: host.der-ripper Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'finish')
2022-08-07 08:11:03.161  - error:  host.der-ripper Caught by controller[1]:     at  GoE.adjustAmpLevelInWatts  (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
2022-08-07 08:11:03.161  - error: host.der-ripper instance system.adapter.go-e.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-08-07 08:11:03.161  - info: host.der-ripper Restart adapter system.adapter.go-e.0 because enabled
2022-08-07 08:11:33.198  - info: host.der-ripper instance system.adapter.go-e.0 started with pid 23867
2022-08-07 08:12:00.011  - error:  go-e.0 (23867) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-08-07 08:12:00.012  - error: go-e.0 (23867) unhandled promise rejection: Cannot read properties of undefined (reading 'finish')
2022-08-07 08:12:00.012  - error: go-e.0 (23867) TypeError: Cannot read properties of undefined (reading 'finish')
at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
2022-08-07 08:12:00.012  - error: go-e.0 (23867) Cannot read properties of undefined (reading 'finish')
2022-08-07 08:12:03.225  - error:  host.der-ripper Caught by controller[0]: This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-08-07 08:12:03.225  - error: host.der-ripper Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'finish')
2022-08-07 08:12:03.225  - error:  host.der-ripper Caught by controller[1]:     at  GoE.adjustAmpLevelInWatts  (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
2022-08-07 08:12:03.225  - error: host.der-ripper instance system.adapter.go-e.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-08-07 08:12:03.225  - info: host.der-ripper Restart adapter system.adapter.go-e.0 because enabled
2022-08-07 08:12:03.225  - warn: host.der-ripper Do not restart adapter system.adapter.go-e.0 because restart loop detected


</body>
</html>

**Comment by luckyheiko** [comment]
Hallo 
auch komm ich trotz manuell gestellter werte
![grafik](https://user-images.githubusercontent.com/26415601/183278364-08eb73f2-577a-4ff9-8de9-cfe67516b451.png)
nicht auf 16A
![grafik](https://user-images.githubusercontent.com/26415601/183278347-824ca9c3-cea8-4b9d-b753-5565c6aefe82.png)

**Comment by luckyheiko** [comment]
> > ![grafik](https://user-images.githubusercontent.com/26415601/178096943-b59c11cd-1d6e-4c48-b86f-126b6d0f353a.png)
> > bei mir wird der PV Ertrag und die Einspeißung an den Smartmetern ausgelesen
> > ![grafik](https://user-images.githubusercontent.com/26415601/178096968-02184126-67ee-4ca1-85c0-b338e4efdbcf.png)
> > hier bekomme ich werte immer mit - (Minus)
> > z.B. -5000W (PV) und -4500W (Einspeißung), würde dann ergeben das ich 500Watt selbst Verbrauche.
> 
> Was sind denn die -3277 in deinem Screenshot PV gesamt, Überschuss?

in dem Fall sind die -3277 die Einspeißung also PV - Hausverbrauch


nicht wundern, hier läuft gerade der Go-E  mit 14,5A
![grafik](https://user-images.githubusercontent.com/26415601/183278557-8cbd30e5-4b02-432e-8219-29e53e67d756.png)

-2167 PV und 1492 werden noch aus dem Netz gezogen (deswegen kein - (minus)

**Comment by luckyheiko** [comment]
also irgendwo hab ich da nen hänger O.o
ich habe nen Kona ( kann nur 1 Phasig laden )

ich habe, wie schon oben geschrieben, die Werte manuel mal eingetragen.
Z.B.
![grafik](https://user-images.githubusercontent.com/26415601/183408468-cd1ef2e6-ef07-4dee-88ff-5930aaae7df3.png)

hier habe ich dann gesehen, das der wert Ampere
![grafik](https://user-images.githubusercontent.com/26415601/183408590-22f6d8d1-275b-443d-a042-395d6e07f44f.png)

sich änder, in dem Fall auf 18A
aber wie kann das sein, das 1000W (2000W-1000W) 18A ergeben?
bei mir sind 1000W (1000/230 = 4,35A) oder rechne ich das 'falsch'?

oder was ich fast noch denke, das er den Verbrauch nicht abzieht, kann das sein?


und auch wieder ewig fehlermedungen im log
![grafik](https://user-images.githubusercontent.com/26415601/183409022-f9af0991-157f-4f8a-8ebe-2c9699633453.png)

**Comment by luckyheiko** [comment]
oder muss hier zwangsweise was im Speicher stehen?
wenn ja, was?
![grafik](https://user-images.githubusercontent.com/26415601/183409748-2cbee925-d7ca-47ea-a2f6-5621830db5eb.png)
