### ISSUE TITLE
Adapter stürtzt bei "oft" Aufruf ab und wird dann disabled.

### ISSUE THREAD

**Issue by maniac-on-moon** [MK-2001/ioBroker.go-e#147]
Hallo,

Setup:
iobroker 5.3.8
Plattform     linux
Betriebssystem    linux
Architektur    arm
CPUs    4
Geschwindigkeit    1500 MHz
Modell    ARMv7 Processor rev 3 (v7l)
RAM    7.71 GB
Node.js    v14.20.0 (Empfohlene Version v16.17.0)
NPM    6.14.17
Aktive Instanzen    14

go-e: 1.0.23

Wirft nach ein "paar" erfolgreichen Durchläufen, wenn ich im blockly
"go-e.0.energy.adjustAmpLevelInWatts" "steuere"  eine Exception und stribt. 
`

2022-08-21 10:15:47.150  - warn: go-e.0 (7660) Sentry enabled. You can switch it off in settings of the adapter.
--
2022-08-21 10:16:24.382  - info: javascript.0 (20314) script.js.Prd.VBS-PV-UeLadung: Laden START, min A: 6
2022-08-21 10:17:34.388  - info: javascript.0 (20314) script.js.Prd.VBS-PV-UeLadung: AMX=6
2022-08-21 10:18:09.388  - info: javascript.0 (20314) script.js.Prd.VBS-PV-UeLadung: AMX=6
2022-08-21 10:18:44.389  - info: javascript.0 (20314) script.js.Prd.VBS-PV-UeLadung: AMX=6
2022-08-21 10:19:19.390  - info: javascript.0 (20314) script.js.Prd.VBS-PV-UeLadung: AMX=6
2022-08-21 10:19:54.390  - info: javascript.0 (20314) script.js.Prd.VBS-PV-UeLadung: AMX=6
2022-08-21 10:20:29.390  - info: javascript.0 (20314) script.js.Prd.VBS-PV-UeLadung: AMX=6
2022-08-21 10:21:04.392  - info: javascript.0 (20314) script.js.Prd.VBS-PV-UeLadung: AMX=6
2022-08-21 10:21:39.392  - info: javascript.0 (20314) script.js.Prd.VBS-PV-UeLadung: DeltaW=1002.52
2022-08-21 10:21:39.416  - error:  go-e.0 (7660) Unhandled promise rejection. This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
2022-08-21 10:21:39.417  - error: go-e.0 (7660) unhandled promise rejection: Cannot read property 'finish' of undefined
2022-08-21 10:21:39.418  - error: go-e.0 (7660) TypeError: Cannot read property 'finish' of undefined
at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
2022-08-21 10:21:39.419  - error: go-e.0 (7660) Cannot read property 'finish' of undefined
2022-08-21 10:21:39.440  - warn: go-e.0 (7660) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-08-21 10:21:39.961  - warn: go-e.0 (7660) get state error: Connection is closed.
2022-08-21 10:21:39.968  - warn: go-e.0 (7660) Could not perform strict object check of state go-e.0.temperatures.tempereature3: DB closed
2022-08-21 10:21:39.969  - warn: go-e.0 (7660) get state error: Connection is closed.
2022-08-21 10:21:39.972  - warn: go-e.0 (7660) Cloud not store temperature array to single values, because of error DB closed
2022-08-21 10:21:39.980  - warn: go-e.0 (7660) Could not perform strict object check of state go-e.0.adapter_in: DB closed
2022-08-21 10:21:39.981  - warn: go-e.0 (7660) get state error: Connection is closed.
2022-08-21 10:21:40.106  - error:  host.iot Caught by controller[0]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-08-21 10:21:40.107  - error: host.iot Caught by controller[1]: TypeError: Cannot read property 'finish' of undefined
2022-08-21 10:21:40.108  - error: host.iot Caught by controller[1]:     at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
2022-08-21 10:21:40.108  - error: host.iot instance system.adapter.go-e.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-08-21 10:21:40.109  - info: host.iot Restart adapter system.adapter.go-e.0 because enabled

`
Der Fehler tritt schon länger auf (3 Monate), der Blockly Code  hat mal funktioniert.

Welche Infos werden noch gebraucht? Was kann ich sammeln?
 

Danke und Beste Grüße
Tom

**Comment by MK-2001** [comment]
Is already fixed in Version 1.0.25
