### ISSUE TITLE
1.0.33 crashes after start

### ISSUE THREAD

**Issue by jlegen** [MK-2001/ioBroker.go-e#232]
after upgrading from 1.0.32 to 1.0.33, instance crashes after start. Reverting to 1.0.32 did work. HW V2 here, API v1 selected…

2024-06-16 21:10:15.778  - ESC[32minfoESC[39m: go-e.0 (3551440) starting. Version 1.0.33 in /usr/local/iobroker/node_modules/iobroker.go-e, node: v18.20.2, js-con
troller: 5.0.19
2024-06-16 21:10:15.811  - ESC[32minfoESC[39m: go-e.0 (3551440) Adapter is staring in Version setByGitHubActions
2024-06-16 21:10:15.812  - ESC[32minfoESC[39m: go-e.0 (3551440) Server: go-echarger.fritz.box
2024-06-16 21:10:15.813  - ESC[32minfoESC[39m: go-e.0 (3551440) Intervall: 30
2024-06-16 21:10:15.813  - ESC[32minfoESC[39m: go-e.0 (3551440) Calculation Method: iob
2024-06-16 21:10:15.859  - ESC[31merrorESC[39m: go-e.0 (3551440) Unhandled promise rejection. This error originated either by throwing inside of an async function
 without a catch block, or by rejecting a promise which was not handled with .catch().
2024-06-16 21:10:15.859  - ESC[31merrorESC[39m: go-e.0 (3551440) unhandled promise rejection: Api V2 is not enabled
2024-06-16 21:10:15.864  - ESC[31merrorESC[39m: go-e.0 (3551440) Error: Api V2 is not enabled
    at GoE.setValueV2 (/usr/local/iobroker/node_modules/iobroker.go-e/main.js:718:35)
    at GoE.onReady (/usr/local/iobroker/node_modules/iobroker.go-e/main.js:101:18)
    at GoE.emit (node:events:517:28)
    at GoE._callReadyHandler (/usr/local/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9095:18)
    at /usr/local/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9074:26
2024-06-16 21:10:15.864  - ESC[31merrorESC[39m: go-e.0 (3551440) Api V2 is not enabled
2024-06-16 21:10:15.918  - ESC[32minfoESC[39m: go-e.0 (3551440) terminating

**Comment by MK-2001** [comment]
1.0.34 is out, for you ;-)

**Comment by jlegen** [comment]
thank you. unfortunately, 1.0.34 does not install...

$ iobroker upgrade go-e@1.0.34

Update go-e from @1.0.32 to @1.0.34

Installing iobroker.go-e@1.0.34... (System call)

npm ERR! code ETARGETnpm ERR! notarget No matching version found for iobroker.go-e@1.0.34.npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-06-17T08_47_46_907Z-debug-0.log Cannot install iobroker.go-e@1.0.34: 1

ERROR: Process exited with code 25


1 info using npm@10.5.0
2 info using node@v18.20.2
...
21 verbose title npm install iobroker.go-e@1.0.34
22 verbose argv "install" "--save-exact" "--loglevel" "error" "iobroker.go-e@1.0.34"
...
51 timing command:install Completed in 14038ms
52 verbose type version
53 verbose stack iobroker.go-e: No matching version found for iobroker.go-e@1.0.34.
53 verbose stack     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
53 verbose stack     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:130:22)
53 verbose stack     at async #nodeFromEdge (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1056:19)
53 verbose stack     at async #buildDepStep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:924:11)
53 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:203:7)
53 verbose stack     at async Promise.all (index 1)
53 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
53 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:153:5)
53 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli-entry.js:61:5)

**Comment by MK-2001** [comment]
@jlegen Please use 1.0.35

**Comment by dft601** [comment]
Thats what I recognized too tomorrow but I saw 1.0.35 and installed manually.

But I always have restarts:

`go-e.1
	2024-06-17 11:17:34.835	error	Api V2 is not enabled
go-e.1
	2024-06-17 11:17:34.834	error	Error: Api V2 is not enabled at GoE.setValueV2 (/opt/iobroker/node_modules/iobroker.go-e/main.js:719:35) at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:101:18) at GoE.emit (node:events:517:28) at GoE._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6343:12) at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6328:14
go-e.1
	2024-06-17 11:17:34.829	error	unhandled promise rejection: Api V2 is not enabled
go-e.1
	2024-06-17 11:17:34.827	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

**Comment by fuchs-1978** [comment]
Same problems here with 1.0.34

<html>
<body>

2024-06-17 06:17:46.340 - error: go-e.0 (125292) Object go-e.0.phaseSwitchModeBuffer is invalid: Default value has to be type "number" but received type "string"
--
2024-06-17 06:17:46.408 - error: go-e.0 (125292) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-06-17 06:17:46.409 - error: go-e.0 (125292) unhandled promise rejection: Api V2 is not enabled
2024-06-17 06:17:46.413 - error: go-e.0 (125292) Error: Api V2 is not enabled
at GoE.setValueV2 (/opt/iobroker/node_modules/iobroker.go-e/main.js:719:35)
at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:101:18)
at GoE.emit (node:events:519:28)
at GoE._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6343:12)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6328:14
2024-06-17 06:17:46.413 - error: go-e.0 (125292) Api V2 is not enabled
2024-06-17 06:17:46.427 - warn: go-e.0 (125292) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-06-17 06:17:46.501 - error: go-e.1 (125298) Object go-e.1.phaseSwitchModeBuffer is invalid: Default value has to be type "number" but received type "string"
2024-06-17 06:17:46.512 - error: go-e.2 (125306) Object go-e.2.phaseSwitchModeBuffer is invalid: Default value has to be type "number" but received type "string"
2024-06-17 06:17:46.550 - error: go-e.1 (125298) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-06-17 06:17:46.550 - error: go-e.1 (125298) unhandled promise rejection: Api V2 is not enabled
2024-06-17 06:17:46.552 - error: go-e.1 (125298) Error: Api V2 is not enabled
at GoE.setValueV2 (/opt/iobroker/node_modules/iobroker.go-e/main.js:719:35)
at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:101:18)
at GoE.emit (node:events:519:28)
at GoE._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6343:12)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6328:14
2024-06-17 06:17:46.553 - error: go-e.1 (125298) Api V2 is not enabled
2024-06-17 06:17:46.566 - error: go-e.2 (125306) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-06-17 06:17:46.567 - error: go-e.2 (125306) unhandled promise rejection: Api V2 is not enabled
2024-06-17 06:17:46.569 - error: go-e.2 (125306) Error: Api V2 is not enabled
at GoE.setValueV2 (/opt/iobroker/node_modules/iobroker.go-e/main.js:719:35)
at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:101:18)
at GoE.emit (node:events:519:28)
at GoE._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6343:12)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6328:14
2024-06-17 06:17:46.569 - error: go-e.2 (125306) Api V2 is not enabled
2024-06-17 06:17:46.575 - warn: go-e.1 (125298) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-06-17 06:17:46.581 - warn: go-e.2 (125306) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-06-17 06:17:46.933 - warn: go-e.0 (125292) get state error: Connection is closed.
2024-06-17 06:17:46.937 - warn: go-e.0 (125292) Could not perform strict object check of state go-e.0.settings.ampere_level1: DB closed
2024-06-17 06:17:46.938 - warn: go-e.0 (125292) get state error: Connection is closed.
2024-06-17 06:17:47.024 - error: host.iobroker0424 instance system.adapter.go-e.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-06-17 06:17:47.025 - info: host.iobroker0424 Restart adapter system.adapter.go-e.0 because enabled
2024-06-17 06:17:47.081 - warn: go-e.1 (125298) get state error: Connection is closed.
2024-06-17 06:17:47.088 - warn: go-e.2 (125306) get state error: Connection is closed.
2024-06-17 06:17:47.128 - warn: go-e.2 (125306) Cloud not store temperature array to single values, because of error DB closed
2024-06-17 06:17:47.189 - error: host.iobroker0424 instance system.adapter.go-e.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-06-17 06:17:47.189 - info: host.iobroker0424 Restart adapter system.adapter.go-e.1 because enabled
2024-06-17 06:17:47.260 - error: host.iobroker0424 instance system.adapter.go-e.2 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-06-17 06:17:47.260 - info: host.iobroker0424 Restart adapter system.adapter.go-e.2 because enabled
2024-06-17 06:18:17.872 - info: host.iobroker0424 instance system.adapter.go-e.0 started with pid 125380
2024-06-17 06:18:17.932 - info: host.iobroker0424 instance system.adapter.go-e.1 started with pid 125387
2024-06-17 06:18:17.939 - info: host.iobroker0424 instance system.adapter.go-e.2 started with pid 125388
2024-06-17 06:18:22.871 - error: go-e.1 (125387) Object go-e.1.phaseSwitchModeBuffer is invalid: Default value has to be type "number" but received type "string"
2024-06-17 06:18:22.929 - error: go-e.1 (125387) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-06-17 06:18:22.929 - error: go-e.1 (125387) unhandled promise rejection: Api V2 is not enabled
2024-06-17 06:18:22.931 - error: go-e.1 (125387) Error: Api V2 is not enabled
at GoE.setValueV2 (/opt/iobroker/node_modules/iobroker.go-e/main.js:719:35)
at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:101:18)
at GoE.emit (node:events:519:28)
at GoE._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6343:12)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6328:14
2024-06-17 06:18:22.932 - error: go-e.1 (125387) Api V2 is not enabled
2024-06-17 06:18:22.943 - warn: go-e.1 (125387) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-06-17 06:18:23.012 - error: go-e.2 (125388) Object go-e.2.phaseSwitchModeBuffer is invalid: Default value has to be type "number" but received type "string"
2024-06-17 06:18:23.078 - error: go-e.2 (125388) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-06-17 06:18:23.079 - error: go-e.2 (125388) unhandled promise rejection: Api V2 is not enabled
2024-06-17 06:18:23.081 - error: go-e.2 (125388) Error: Api V2 is not enabled
at GoE.setValueV2 (/opt/iobroker/node_modules/iobroker.go-e/main.js:719:35)
at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:101:18)
at GoE.emit (node:events:519:28)
at GoE._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6343:12)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6328:14
2024-06-17 06:18:23.081 - error: go-e.2 (125388) Api V2 is not enabled
2024-06-17 06:18:23.094 - warn: go-e.2 (125388) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-06-17 06:18:23.130 - error: go-e.0 (125380) Object go-e.0.phaseSwitchModeBuffer is invalid: Default value has to be type "number" but received type "string"
2024-06-17 06:18:23.176 - error: go-e.0 (125380) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-06-17 06:18:23.177 - error: go-e.0 (125380) unhandled promise rejection: Api V2 is not enabled
2024-06-17 06:18:23.178 - error: go-e.0 (125380) Error: Api V2 is not enabled
at GoE.setValueV2 (/opt/iobroker/node_modules/iobroker.go-e/main.js:719:35)
at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:101:18)
at GoE.emit (node:events:519:28)
at GoE._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6343:12)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6328:14
2024-06-17 06:18:23.178 - error: go-e.0 (125380) Api V2 is not enabled


</body>
</html>

**Comment by jlegen** [comment]
> @jlegen Please use 1.0.35 I tried to replace 1.0.34, what did not work.

exact same issue like in 1st post with 1.0.35…
