### ISSUE TITLE
Ich bekomme seit 2 Tagen plötzlich immer mehr warnmeldungen 

### ISSUE THREAD

**Issue by weindler** [MK-2001/ioBroker.go-e#46]
Adapter Version 1.04
Node.js
    v12.22.1
NPM
    6.14.12

go-e.0 | 2021-05-30 10:01:02.192 | warn | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
go-e.0 | 2021-05-30 10:01:02.192 | warn | at runMicrotasks (&lt;anonymous&gt;)
go-e.0 | 2021-05-30 10:01:02.192 | warn | at GoE.processStatusObject (/opt/iobroker/node_modules/iobroker.go-e/main.js:318:25)
go-e.0 | 2021-05-30 10:01:02.192 | warn | at PQueue.add (/opt/iobroker/node_modules/p-queue/dist/index.js:152:16)
go-e.0 | 2021-05-30 10:01:02.192 | warn | at new Promise (&lt;anonymous&gt;)
go-e.0 | 2021-05-30 10:01:02.192 | warn | at /opt/iobroker/node_modules/p-queue/dist/index.js:171:18
go-e.0 | 2021-05-30 10:01:02.192 | warn | at PQueue._tryToStartAnother (/opt/iobroker/node_modules/p-queue/dist/index.js:105:17)
go-e.0 | 2021-05-30 10:01:02.192 | warn | at run (/opt/iobroker/node_modules/p-queue/dist/index.js:157:104)
go-e.0 | 2021-05-30 10:01:02.192 | warn | at /opt/iobroker/node_modules/iobroker.go-e/main.js:318:99
go-e.0 | 2021-05-30 10:01:02.192 | warn | (31771) Error in go.e: "Cannot read property '0' of undefined"; Stack: TypeError: Cannot read property '0' of undefined
go-e.0 | 2021-05-30 10:01:02.145 | warn | (31771) Cloud not store synctime, because of error object null is not iterable (cannot read property Symbol(Symbol.i

**Comment by weindler** [comment]
erledigt, einer meiner wlan repeater macht mir sorgen, jetzt ist der go-e mal verbunden und mal nicht, zumindestens könnte ich mir das vorstellen, habe mal die repeater anders angeordnet, zumindestens wäre jetzt das WLAN bisher aktiv. Anosnten würde ich mal sagen es ist erledigt, wenn nciht mache ich ein neues issue auf.
